# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# fill_tool.py
# Created on: 2017-09-13 12:34:42.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: fill_tool <mary463> <Fill_mary4631_tif>
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import time
t0 = time.time()
arcpy.CheckOutExtension("Spatial")

dem = "C:\\PhD\\junk\\mary463"

z_lim = "C:\\PhD\\junk\\marydpth"

sinkmax = arcpy.GetRasterProperties_management(z_lim, "MAXIMUM")

sinkm = sinkmax.getOutput(0)

print sinkm

# Script arguments
mary_fill = "C:\\PhD\\junk\\mary_fill.tif" # provide a default value if unspecified

# Local variables:
Z_limit = str(sinkm + 0.3)

# Process: Fill
arcpy.gp.Fill_sa(dem, mary_fill, Z_limit)

print ""
print "Time taken: " "hours: %i, minutes: %i, seconds: %i" %(int((time.time()-t0)/3600), int(((time.time()-t0)%3600)/60), int((time.time()-t0)%60))
